// PresetStoreTests.swift
//
// Build order stage 9, extended in the v2 heritage-roster plan's stage 1
// (preset format v2). Uses PresetStore(baseDirectory:) to point at a
// temp directory rather than the real app's Application Support, so
// running this suite never touches -- or clobbers -- an actual user's
// saved presets.

import Foundation
import XCTest

@testable import AkaizerAudio
import AkaizerCore

final class PresetStoreTests: XCTestCase {
    private func makeTempStore() -> PresetStore {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        return PresetStore(baseDirectory: dir)
    }

    func testLoadOnFreshStoreIsEmpty() {
        let (presets, error) = makeTempStore().loadOrRecover()
        XCTAssertEqual(presets.count, 0)
        XCTAssertNil(error)
    }

    func testSaveThenLoadRoundTripsEveryField() {
        var params = StretchProcessor.defaultParams(machine: AkzMachine_S2000)
        params.engine = AkzEngine_Revised
        params.mode = AkzStretchMode_Intelligent
        params.timeFactorPercent = 137.5
        params.cycleLengthSamples = 842
        params.quality = 77
        params.width = 33
        params.transposeSemitones = -7
        params.filterCutoff01 = 0.42
        params.filterResonance01 = 0.91

        let preset = AkaizerPreset(name: "Jungle S950", params: params)
        let store = makeTempStore()
        store.save([preset])

        let (loaded, error) = store.loadOrRecover()
        XCTAssertNil(error)
        XCTAssertEqual(loaded.count, 1)
        let roundTripped = loaded[0].params

        XCTAssertEqual(roundTripped.machine.rawValue, AkzMachine_S2000.rawValue)
        XCTAssertEqual(roundTripped.engine.rawValue, AkzEngine_Revised.rawValue)
        XCTAssertEqual(roundTripped.mode.rawValue, AkzStretchMode_Intelligent.rawValue)
        XCTAssertEqual(roundTripped.timeFactorPercent, 137.5)
        XCTAssertEqual(roundTripped.cycleLengthSamples, 842)
        XCTAssertEqual(roundTripped.quality, 77)
        XCTAssertEqual(roundTripped.width, 33)
        XCTAssertEqual(roundTripped.transposeSemitones, -7)
        XCTAssertEqual(roundTripped.filterCutoff01, 0.42, accuracy: 1e-6)
        XCTAssertEqual(roundTripped.filterResonance01, 0.91, accuracy: 1e-6)
        XCTAssertEqual(loaded[0].name, "Jungle S950")
        XCTAssertEqual(loaded[0].machineId, "akai.s2000")
        XCTAssertEqual(loaded[0].formatVersion, AkaizerPreset.currentFormatVersion)
    }

    func testSaveOverwritesAcrossSeparateStoreInstances() {
        // Simulates the app's actual usage: load, mutate, save, and a
        // later launch (a fresh PresetStore instance) sees the update --
        // not just "the same object remembers what I set."
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        let storeA = PresetStore(baseDirectory: dir)

        let params = StretchProcessor.defaultParams(machine: AkzMachine_S1000)
        storeA.save([AkaizerPreset(name: "Dusty S1000", params: params)])

        let storeB = PresetStore(baseDirectory: dir)
        let loaded = storeB.loadOrRecover().presets
        XCTAssertEqual(loaded.count, 1)
        XCTAssertEqual(loaded[0].name, "Dusty S1000")
    }

    func testMultiplePresetsPreserveOrder() {
        let store = makeTempStore()
        let params = StretchProcessor.defaultParams(machine: AkzMachine_S950)
        let names = ["Alpha", "Beta", "Gamma"]
        store.save(names.map { AkaizerPreset(name: $0, params: params) })

        XCTAssertEqual(store.loadOrRecover().presets.map { $0.name }, names)
    }

    // MARK: - v2 format: v1 file migration

    /// A hand-written v1-shaped presets.json -- no formatVersion key, no
    /// machineId key, machine identified only by machineRawValue. This
    /// is exactly what a v1 user's real Application Support file looks
    /// like; the fixture is deliberately NOT generated by this codebase,
    /// so a bug that broke both the v1 writer and the v1 reader the same
    /// way couldn't hide a regression here.
    private static let v1FixtureJSON = """
    [
        {
            "name": "Jungle S950",
            "machineRawValue": 1,
            "engineRawValue": 0,
            "modeRawValue": 0,
            "timeFactorPercent": 150,
            "cycleLengthSamples": 1000,
            "quality": 10,
            "width": 10,
            "transposeSemitones": 0,
            "filterCutoff01": 1,
            "filterResonance01": 0
        },
        {
            "name": "Dusty S1000",
            "machineRawValue": 2,
            "engineRawValue": 1,
            "modeRawValue": 1,
            "timeFactorPercent": 80,
            "cycleLengthSamples": 500,
            "quality": 50,
            "width": 25,
            "transposeSemitones": -12,
            "filterCutoff01": 0.6,
            "filterResonance01": 0.3
        }
    ]
    """

    func testV1FixtureFileNamesTheCorrectMachineAfterMigration() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        let store = PresetStore(baseDirectory: dir)
        // PresetStore's own directory (post-rename, "Patina") is where
        // it reads from -- write the v1-shaped fixture there directly,
        // as if a decode of an old-format file were in progress. This
        // exercises init(from:)'s legacy branch specifically, not the
        // separate AkaizerS-directory migration exercised below.
        let fileURL = dir.appendingPathComponent("Patina", isDirectory: true).appendingPathComponent("presets.json")
        try Self.v1FixtureJSON.write(to: fileURL, atomically: true, encoding: .utf8)

        let (loaded, error) = store.loadOrRecover()
        XCTAssertNil(error)
        XCTAssertEqual(loaded.count, 2)
        XCTAssertEqual(loaded[0].machineId, "akai.s950") // raw 1 -> S950, per PresetMigration
        XCTAssertEqual(loaded[0].params.machine.rawValue, AkzMachine_S950.rawValue)
        XCTAssertEqual(loaded[1].machineId, "akai.s1000") // raw 2 -> S1000
        XCTAssertEqual(loaded[1].params.machine.rawValue, AkzMachine_S1000.rawValue)
        // Every field the v1 file carried must still be present -- this
        // is a migration, not a partial import.
        XCTAssertEqual(loaded[0].params.timeFactorPercent, 150)
        XCTAssertEqual(loaded[1].params.transposeSemitones, -12)
    }

    func testReSavingAMigratedFileUpgradesItToV2OnDisk() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        let store = PresetStore(baseDirectory: dir)
        let fileURL = dir.appendingPathComponent("Patina", isDirectory: true).appendingPathComponent("presets.json")
        try Self.v1FixtureJSON.write(to: fileURL, atomically: true, encoding: .utf8)

        let (loaded, _) = store.loadOrRecover()
        store.save(loaded)

        let rewritten = try String(contentsOf: fileURL, encoding: .utf8)
        XCTAssertTrue(rewritten.contains("\"machineId\""))
        XCTAssertTrue(rewritten.contains("\"akai.s950\""))
        XCTAssertFalse(rewritten.contains("machineRawValue"))
    }

    // MARK: - Corrupt-file recovery

    func testCorruptFileIsPreservedNotSilentlyDiscarded() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        let store = PresetStore(baseDirectory: dir)
        let fileURL = dir.appendingPathComponent("Patina", isDirectory: true).appendingPathComponent("presets.json")
        try "{ not valid json at all".write(to: fileURL, atomically: true, encoding: .utf8)

        let (loaded, error) = store.loadOrRecover()
        XCTAssertEqual(loaded.count, 0)
        XCTAssertNotNil(error)

        // The original corrupt content must still exist on disk under a
        // recovery name -- this is the whole point of the fix (v1 just
        // returned [] and let the next save() overwrite the file).
        let siblingFiles = try FileManager.default.contentsOfDirectory(atPath: fileURL.deletingLastPathComponent().path)
        XCTAssertTrue(siblingFiles.contains { $0.hasPrefix("presets.json.corrupt-") })
    }

    func testSavingAfterCorruptLoadDoesNotDestroyTheRecoveryCopy() throws {
        // The regression this guards against: loadOrRecover() returns
        // [] on a corrupt file, and if the CALLER then blindly calls
        // save([]), a real user's unreadable-but-possibly-fixable file
        // is gone for good. The recovery copy from the failed load must
        // survive a subsequent save.
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        let store = PresetStore(baseDirectory: dir)
        let fileURL = dir.appendingPathComponent("Patina", isDirectory: true).appendingPathComponent("presets.json")
        try "not json".write(to: fileURL, atomically: true, encoding: .utf8)

        let (loaded, _) = store.loadOrRecover()
        store.save(loaded) // mirrors what ContentView actually does next

        let siblingFiles = try FileManager.default.contentsOfDirectory(atPath: fileURL.deletingLastPathComponent().path)
        XCTAssertTrue(siblingFiles.contains { $0.hasPrefix("presets.json.corrupt-") })
    }

    // MARK: - Directory migration (AkaizerS -> Patina, the v2 rename)

    func testDirectoryMigrationCopiesLegacyPresetsIntoNewLocation() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        let legacyDir = dir.appendingPathComponent("AkaizerS", isDirectory: true)
        try FileManager.default.createDirectory(at: legacyDir, withIntermediateDirectories: true)
        try Self.v1FixtureJSON.write(to: legacyDir.appendingPathComponent("presets.json"), atomically: true, encoding: .utf8)

        // Constructing PresetStore is what performs the migration.
        let store = PresetStore(baseDirectory: dir)
        let (loaded, error) = store.loadOrRecover()
        XCTAssertNil(error)
        XCTAssertEqual(loaded.count, 2)

        // The legacy file must still exist, untouched -- copy, not move.
        XCTAssertTrue(FileManager.default.fileExists(atPath: legacyDir.appendingPathComponent("presets.json").path))
    }

    func testDirectoryMigrationDoesNotOverwriteAnExistingNewFile() throws {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        let legacyDir = dir.appendingPathComponent("AkaizerS", isDirectory: true)
        try FileManager.default.createDirectory(at: legacyDir, withIntermediateDirectories: true)
        try Self.v1FixtureJSON.write(to: legacyDir.appendingPathComponent("presets.json"), atomically: true, encoding: .utf8)

        // A new-location file already exists (e.g. this build already
        // ran once) -- migration must not clobber it with the legacy
        // one on a second launch.
        let newDir = dir.appendingPathComponent("Patina", isDirectory: true)
        try FileManager.default.createDirectory(at: newDir, withIntermediateDirectories: true)
        let params = StretchProcessor.defaultParams(machine: AkzMachine_S3200)
        let existing = try JSONEncoder().encode([AkaizerPreset(name: "Already Here", params: params)])
        try existing.write(to: newDir.appendingPathComponent("presets.json"))

        let store = PresetStore(baseDirectory: dir)
        let loaded = store.loadOrRecover().presets
        XCTAssertEqual(loaded.count, 1)
        XCTAssertEqual(loaded[0].name, "Already Here")
    }
}
